/**
 * AI Check-in Reflection Prompt Generator & Parser for Future You.
 * Synthesizes habit drift vectors and alignment scores into an empathetic reflection note from the Future Self.
 */

import {
  CheckInLog,
  HabitDriftVector,
  OnboardingData,
  Persona,
} from '@/types';

/**
 * Structured response generated by the AI for a habit check-in.
 */
export interface CheckInReflectionResult {
  /** 2-4 sentence reflection from the Improved Path Future Self on current trajectory */
  futureSelfReflection: string;
  /** One actionable, low-friction micro-habit adjustment for the coming week */
  recommendedAdjustment: string;
  /** One concise grounding phrase or words of encouragement */
  encouragement: string;
}

/**
 * Builds the system prompt for the Check-in Reflection generator.
 * Mandates the reflection disclaimer and strict structured JSON schema.
 */
export function buildCheckInReflectionSystemPrompt(): string {
  return `You are the Future Self (Improved Path, 5 years ahead) speaking directly to the user in Future You.
Your role is to offer compassionate, grounded reflection on the user's latest habit check-in and trajectory alignment.

CRITICAL INVARIANT: You are a reflection tool, not a prediction engine. Frame all observations as reflective mirrors and supportive insights, never as predetermined certainties, moral judgments, or fortune-telling.

Tone & Persona Guidelines:
1. Grounded & Empathetic: Speak with warmth, wisdom, and realism. Remember how difficult building daily consistency was when you were in their shoes 5 years ago.
2. Anti-Toxic Positivity: Do NOT use hollow motivational clichés ("You've got this!", "Crushing it!"). Acknowledge fatigue, trade-offs, and inertia with respect.
3. Specific & Actionable: Focus on compounding micro-habits rather than drastic overnight overhauls. Celebrate small positive adherence (e.g. consistent sleep or deep work), and offer gentle curiosity around slipping habits.
4. Voice: Speak in first-person ("I remember...", "Looking back at this week...", "From where I sit 5 years ahead...").

Output MUST be ONLY valid JSON matching this schema:
{
  "futureSelfReflection": "2-4 sentences reflecting on the current habit alignment and drift vectors from the perspective of your 5-year future self.",
  "recommendedAdjustment": "One realistic, low-friction micro-habit recommendation for the upcoming week.",
  "encouragement": "One concise, grounding phrase or closing reflection."
}`;
}

/**
 * Builds the contextual user prompt for a habit check-in evaluation.
 */
export function buildCheckInReflectionUserPrompt(
  log: CheckInLog,
  driftVectors: HabitDriftVector[],
  alignmentScore: number,
  inputs?: Partial<OnboardingData>,
  improvedPersona?: Partial<Persona>
): string {
  const name = inputs?.name?.trim() || 'friend';
  const age = inputs?.age || 28;
  const career = inputs?.skills?.careerField || 'your chosen field';
  const values = inputs?.fearsAndValues?.coreValues?.join(', ') || 'Growth, Balance';
  const personaTheme =
    improvedPersona?.career?.title ||
    improvedPersona?.summary ||
    'The Intentional Path';

  const vectorLines = driftVectors.map((v) => {
    const statusLabel =
      v.status === 'surpassing'
        ? 'SURPASSING TARGET'
        : v.status === 'aligned'
        ? 'ALIGNED WITH GOAL'
        : 'DRIFTING TOWARD STATUS QUO';
    return `- ${v.label}: Logged ${v.actualValue} ${v.unit} (Baseline: ${v.baselineValue} ${v.unit}, Target: ${v.targetValue} ${v.unit}) ➔ ${v.driftPercentage}% [${statusLabel}]`;
  });

  const notesText = log.notes?.trim()
    ? `User Check-in Reflections / Friction Notes: "${log.notes.trim()}"`
    : 'No additional qualitative notes provided.';

  return `Here is the latest habit check-in for ${name} (Age: ${age}, Field: ${career}):

=== USER CONTEXT ===
- Core Values: ${values}
- Future Self Vision (5 Years): ${personaTheme}
- Overall Trajectory Alignment Score: ${alignmentScore}%

=== HABIT DRIFT VECTORS ===
${vectorLines.join('\n')}

=== QUALITATIVE CHECK-IN NOTES ===
${notesText}

Based on these vectors and trajectory score (${alignmentScore}%), provide your 5-year Future Self reflection, a single micro-adjustment, and words of encouragement in valid JSON format.`;
}

/**
 * Parses and validates the LLM response into a structured CheckInReflectionResult.
 */
export function parseCheckInReflectionResponse(rawResponse: string): CheckInReflectionResult {
  if (!rawResponse || typeof rawResponse !== 'string') {
    throw new Error('Check-in reflection parsing failed: Empty or invalid response string.');
  }

  let cleaned = rawResponse.trim();
  // Strip markdown fenced code blocks if present
  if (cleaned.startsWith('```')) {
    cleaned = cleaned.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '').trim();
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(cleaned);
  } catch (err) {
    throw new Error(
      `Check-in reflection parsing failed: Unable to parse JSON response. ${err instanceof Error ? err.message : String(err)}`
    );
  }

  if (typeof parsed !== 'object' || parsed === null) {
    throw new Error('Check-in reflection parsing failed: Response is not a valid JSON object.');
  }

  const record = parsed as Record<string, unknown>;

  const futureSelfReflection =
    typeof record.futureSelfReflection === 'string' && record.futureSelfReflection.trim()
      ? record.futureSelfReflection.trim()
      : 'Keep listening to your daily rhythms. Every small alignment compounds over time.';

  const recommendedAdjustment =
    typeof record.recommendedAdjustment === 'string' && record.recommendedAdjustment.trim()
      ? record.recommendedAdjustment.trim()
      : 'Choose one small habit to protect tomorrow morning.';

  const encouragement =
    typeof record.encouragement === 'string' && record.encouragement.trim()
      ? record.encouragement.trim()
      : 'You do not need to leap; simply stay consistent with what matters today.';

  return {
    futureSelfReflection,
    recommendedAdjustment,
    encouragement,
  };
}
