/**
 * Life Model composite structure generated by AI.
 */

import { OnboardingData } from './onboarding.types';
import { Persona } from './persona.types';

/**
 * An interactive habit lever slider that recalculates simulated futures.
 */
export interface HabitLever {
  /** Unique identifier for the lever (e.g., 'sleep-hours', 'study-hours') */
  id: string;
  /** Human-readable display label */
  label: string;
  /** Minimum slider value */
  min: number;
  /** Maximum slider value */
  max: number;
  /** Slider increment step */
  step: number;
  /** Current value derived from onboarding or user adjustment */
  currentValue: number;
  /** Measurement unit (e.g. 'hours', 'hrs/week', '%') */
  unit: string;
}

/**
 * Top-level generated life simulation model comparing Current and Improved paths.
 */
export interface LifeModel {
  /** Unique identifier for this life model generation */
  id: string;
  /** ISO-8601 creation timestamp */
  createdAt: string;
  /** Baseline self-reported onboarding data used to generate the model */
  inputs: OnboardingData;
  /** Five-year trajectory continuing baseline habits */
  currentPath: Persona;
  /** Five-year trajectory adopting optimal habit adjustments */
  improvedPath: Persona;
  /** Configurable levers allowing dynamic futures recalculation */
  habitLevers: HabitLever[];
}
